# List the pdf's to build. foo.tex will produce foo.pdf
TARGETS = RFC_FancyCron.pdf

# List the files included in the slides
DEPS =

# Relative path to the LaTeX Ultimaade documentclass setup files
# You should not need to touch this
#RELPATH = ../templates-ultimaade/latex/
RELPATH = ../templates-bouygues/latex


# You should not touch this either
include $(RELPATH)/Makefile.LaTeX
