# List the pdf's to build. foo.tex will produce foo.pdf
TARGETS = foo.pdf

# List the files included in the slides
DEPS = somePicture.png someSound.flac someOtherPicture.png

# Relative path to the LaTeX koala documentclass setup files
# You should not need to touch this
RELPATH = $(shell svn root)/templates-ultimaade/latex/

# You should not touch this either
include $(RELPATH)/Makefile.LaTeX
